# Generated by Django 3.0.3 on 2021-03-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterpreneur_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=60, null=True, verbose_name='email')),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('date_incorporation', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('turnover', models.CharField(blank=True, max_length=100, null=True)),
                ('journey', models.CharField(blank=True, max_length=100, null=True)),
                ('achievements', models.CharField(blank=True, max_length=100, null=True)),
                ('awards', models.CharField(blank=True, max_length=100, null=True)),
                ('revenue', models.CharField(blank=True, max_length=100, null=True)),
                ('vision', models.CharField(blank=True, max_length=100, null=True)),
                ('nomination', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Startup_app_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=60, null=True, verbose_name='email')),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('date_incorporation', models.CharField(blank=True, max_length=100, null=True)),
                ('problem_solving', models.CharField(blank=True, max_length=100, null=True)),
                ('solution', models.CharField(blank=True, max_length=100, null=True)),
                ('uniqueness', models.CharField(blank=True, max_length=100, null=True)),
                ('advantages', models.CharField(blank=True, max_length=100, null=True)),
                ('operation_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('revenue', models.CharField(blank=True, max_length=100, null=True)),
                ('startup_img', models.ImageField(blank=True, null=True, upload_to='awardimg/')),
                ('vid_link', models.CharField(blank=True, max_length=100, null=True)),
                ('pitch_startup', models.CharField(blank=True, max_length=100, null=True)),
                ('folder_file', models.FileField(blank=True, null=True, upload_to='pitchfile')),
            ],
        ),
    ]
