# Generated by Django 3.0.3 on 2021-03-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_auto_20210307_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpreneur_form',
            name='achievements',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='enterpreneur_form',
            name='awards',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='enterpreneur_form',
            name='impact',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='enterpreneur_form',
            name='journey',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='enterpreneur_form',
            name='nomination',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='enterpreneur_form',
            name='vision',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='startup_app_form',
            name='advantages',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='startup_app_form',
            name='operation_stage',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='startup_app_form',
            name='problem_solving',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='startup_app_form',
            name='revenue',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='startup_app_form',
            name='solution',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='startup_app_form',
            name='uniqueness',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
