# Generated by Django 3.0.3 on 2021-03-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_auto_20210309_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup_app_form',
            name='vid_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
