# Generated by Django 3.0.3 on 2021-05-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounting', '0002_auto_20210511_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionideanest',
            name='recording_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sessionideanest',
            name='recording_pw',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
